#!/usr/bin/env bash

set -e

PREFIX="$(hostname)_"

usage() {
  cat <<EOF
Usage: $0 <help|status|backup|prune>

Commands:
  status  Show number of archives, their resource usage and the date of
          the first and last archive
  backup  Create a new timestamped archive based on the commands and
          paths given in /etc/snapback.conf
  prune   Prunes archives keeping one per month, one par day this month and
          every archive for the current day
EOF
}

status() {
  local archives="$(tarsnap --list-archives 2>/dev/null | sort -nr)"

  if [ -z "$archives" ]; then
    exit 0
  fi

  local total=$(wc -l <<<"$archives")
  local first=$(tail -n1 <<<"$archives")
  local last=$(head -n1 <<<"$archives")
  local sizes=$(tarsnap --print-stats --humanize-numbers 2>/dev/null \
                | grep -oE '[0-9.]+ [a-zA-Z]{2}')

  println() {
    printf "%-30s%20s\n" "$1:" "$2"
  }

  datefmt() {
    local stamp=${1#$PREFIX}
    printf $(date -d @$stamp +'%F %R')
  }

  println "Number of archives" "$total"
  println "Total raw" "$(echo "$sizes" | sed -n 1p)"
  println "Total compressed" "$(echo "$sizes" | sed -n 2p)"
  println "Deduped raw" "$(echo "$sizes" | sed -n 3p)"
  println "Deduped compressed" "$(echo "$sizes" | sed -n 4p)"
  println "From" "$(datefmt $first)"
  println "To" "$(datefmt $last)"
  printf "%50s\n" | tr ' ' '-'

  local width=${#total}
  for name in ${archives}; do
    printf "%${width}s.%$((49-$width))s\n" "$((total--))" "$(datefmt $name)\n"
  done
}

backup() {
  :
}

prune() {
  :
}

case $1 in
  help|-h|--help)
    usage
    ;;
  status|s)
    status
    ;;
  backup|b)
    backup
    ;;
  prune|p)
    prune
    ;;
  *)
    usage
    exit 64
    ;;
esac
